### ISSUE TITLE
Bug: World destruction leads to invalid indexing

### ISSUE THREAD

**Issue by mikhail-dcl** [genaray/Arch#118]
**Reproduction steps:**

- Create several worlds
- Have a system that uses `EntityExtensions` API
- Destroy not the last world, the first one for example
- Observe the exception (here `Add<T>` is used)

```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <cbc72d4a9767498db39486e941a498e3>:0)
Arch.Core.Extensions.EntityExtensions.Add[T] (Arch.Core.Entity& entity, T& cmp) (at D:/Decentraland/ArchECS/Arch/src/Arch/Core/Extensions/EntityExtensions.cs:205)
...
Arch.Core.World.InlineEntityQuery[T,T0] (Arch.Core.QueryDescription& description, T& iForEach) (at D:/Decentraland/ArchECS/Arch/src/Arch/Arch.SourceGen/Arch.SourceGen.QueryGenerator/Acessors.g.cs:17280)
```

**Why it happens**
- The world id is embedded into an entity
- The world equals an index in the world's list
- When the world is destroyed indices are not adjusted

**Workaround**
- Use a Pure ECS approach without the `World` embedded into an entity

**Potential Solution**
- Adjust the world id
- Iterate over all entities and adjust the stored world id (might be very expensive)

**Comment by mikhail-dcl** [comment]
I think changing to Dictionary will be the fastest solution

**Comment by genaray** [comment]
Thanks for reporting! :) 

Well a dictionary is incredible slow. I would prefer two different solutions, either removing a world just sets it spot in the list to null, but does not remove it completely or the list is replaced by an array and set to null. Destroyed world ids could also end up in a queue for being recycled to fill empty spots.

**Comment by mikhail-dcl** [comment]
Hey @genaray 
I like your proposal.
The only things I would like to emphasize and know your opinion on are:

- If the ids are recycled it will be great to reutilize entities bumping up their version for interoperability/storing reasons
- It may be worth thinking about worlds reusing: so the destroyed world would not be `GC`'ed but stored in a recycling queue; it would cover the first need of entities recycling

**Comment by genaray** [comment]
> * If the ids are recycled it will be great to reutilize entities bumping up their version for interoperability/storing reasons
Do you mean that once a world is being recycled/destroyed entities of this world should increase their version by one to indicate that there was a change? 

> * It may be worth thinking about worlds reusing: so the destroyed world would not be `GC`'ed but stored in a recycling queue; it would cover the first need of entities recycling

I agree with this one here. However this should be handled as an additional "feature" or "refactor", ill create a ticket for this later on ^^ 

b1e88aafb0530a8d355b015ac04fd0bcbf163a3d hould fix this bug.
`World.Id` is now being recycled and Worlds are not moved, so the bug should be fixed.
