### ISSUE TITLE
Recommended way to query specific entities?

### ISSUE THREAD

**Issue by micka190** [genaray/Arch#119]
I've been looking through the documentation and the GitHub issues, but I haven't managed to find anything about this (apologies if I've missed it):

Is there a recommended way to query specific entities by some kind of identifier?

Assuming I have some kind of unique identifier (an `Entity.Id`, a `Guid` property, etc.), what is the recommended way of getting a specific entity from the `World`? Should I use a `QueryDescription` and find the specific entity through iteration? Is there some kind of predicate parameter I can pass to a `QueryDescription`? (i.e. `new QueryDescription().WithExclusive<Person>(Id)`)?

**Comment by genaray** [comment]
> I've been looking through the documentation and the GitHub issues, but I haven't managed to find anything about this (apologies if I've missed it):
> 
> Is there a recommended way to query specific entities by some kind of identifier?
> 
> Assuming I have some kind of unique identifier (an `Entity.Id`, a `Guid` property, etc.), what is the recommended way of getting a specific entity from the `World`? Should I use a `QueryDescription` and find the specific entity through iteration? Is there some kind of predicate parameter I can pass to a `QueryDescription`? (i.e. `new QueryDescription().WithExclusive<Person>(Id)`)?

Yep iteration is the way to go :) Or some kind of custom datastructure.
E.g. when you use custom Guids you could store them in a map to quickly convert a Guid to its entity ^^

**Comment by micka190** [comment]
I guess [the upcoming changes to introduce relationships](https://github.com/genaray/Arch/pull/111) will probably resolve this in a cleaner way.

In the meantime, would using `EntityReference`s work better, since I'd just have access to the target `Entity` directly through the property (and be able to call things like `Set()` and `Add()` on it directly)? Or are those intended for other things than relationships?

**Comment by genaray** [comment]
> I guess [the upcoming changes to introduce relationships](https://github.com/genaray/Arch/pull/111) will probably resolve this in a cleaner way.
> 
> In the meantime, would using `EntityReference`s work better, since I'd just have access to the target `Entity` directly through the property (and be able to call things like `Set()` and `Add()` on it directly)? Or are those intended for other things than relationships?

Sorry for the late reply. Yes in the meantime just use EntityReference ^^ 
Theres also now a "Dangerous" extension to create entity structs yourself... that way you could also target entities directly based on the usecase. But its originally meant for other purposes like persistence.
