### ISSUE TITLE
[bug] Creating Worlds in parallel can result in worlds with duplicate Ids

### ISSUE THREAD

**Issue by micka190** [genaray/Arch#120]
I've run into a bit of a problem with Unit Testing code that uses the `World` object in xUnit. Some of my tests were randomly failing in different test files, and I've narrowed it down to `Id` collisions with `World` instances that are running in parallel.

There doesn't seem to be any mechanism in place to prevent `World.Create()` from generating duplicate Ids if 2 methods call it in parallel. 

[In 1.2.5's code](https://github.com/genaray/Arch/blob/adb9e872deb14bf9df60875389545497b58658f0/src/Arch/Core/World.cs#L139-L146), both calls would result in the same Id, since `World.Worlds.Count` would have the same value at call time.

[The master branch's code](https://github.com/genaray/Arch/blob/b1e88aafb0530a8d355b015ac04fd0bcbf163a3d/src/Arch/Core/World.cs#L149-L167) seems to have changed it to re-use recycled Ids, but also doesn't protect against Id collisions.

If this is the expected behavior, it might be worth mentioning in the docs for `World`, since it can cause issues with testing frameworks.

I'm not super familiar with NUnit (which this project uses), but I'm assuming it isn't configured to run these tests in parallel?

As a workaround, I've made these test classes a part of the same `[Collection]`, which forces them to run sequentially instead of in parallel.

**Comment by genaray** [comment]
Well thats right, the world itself is not threadsafe, neither their creation or destruction. 
Never thought that this would become a issue. However this should be easy to fix. For now you could also just wrap the destruction and creation of worlds in locks to prevent this happening ^^

**Comment by micka190** [comment]
> Well thats right, the world itself is not threadsafe, neither their creation or destruction.

That's fair lol

It's not really a problem in my app, it's just an issue in the Unit Tests themselves.

>For now you could also just wrap the destruction and creation of worlds in locks to prevent this happening ^^

I did give that a try, and I'm admittedly not super familiar with C#'s threading practices so maybe I did it wrong, but I ran into some weirdness where the problem persisted.

I would have expected this to work:

```cs

// Helper file
public class WorldCreateHelper
{
    private readonly object myLock = new();

    public World ParallelSafeCreate()
    {
        lock(myLock)
        {
            return World.Create();
        }
    }
}

// Test file
public class SomeTests : IClassFixture<WorldCreateHelper>
{
    public SomeTests(WorldCreateHelper helper)
    {
        var world = helper.ParallelSafeCreate();
        // ...
    }

    // ...
}
```

But it didn't work...

¯\\_(ツ)_/¯

I'm guessing it has to do with how xUnit was handling my helper fixture that wrapped around `World.Create()`, since the `lock(object)` documentation seems pretty straightforward.

To be fair, I don't really expect the `[Collection]` solution to be much a problem. it'll run tests where I need a `World` instance sequentially, but they're unit tests so I don't really expect to see much of a performance problem because they're not in parallel.

**Comment by genaray** [comment]
Thats weird, normally this should work. Unfortunately i dont have that much threading experience either.
I assume that xUnit behaves way different. NUnit does mostly run them in sequence which is quite nice, at least for archs usecase ^^
