### ISSUE TITLE
Null reference in SubscribeComponentAdded callback

### ISSUE THREAD

**Issue by akderebur** [genaray/Arch#122]
Hello. I encountered a small issue with event callbacks. When adding a component to an already existing Entity, the SubscribeComponentAdded event seems to trigger twice. First with a null reference for the component and the second with the correct value.

My event subscription looks like this. Sprite is a class in this case.:
```
            GameWorld.SubscribeComponentAdded((in Entity entity, ref Sprite sprite) =>
            {
                Console.WriteLine("Added");
                if (sprite == null)
                    Console.WriteLine("Null");
                else
                    Console.WriteLine("Not null");
            });
```

And component addition happens like this:
```   
        public static void AddSprite(in Entity entity)
        {
            Sprite sprite = new Sprite();
            entity.Add<Sprite>(sprite);
        }
```

When the AddSprite is executed the callback triggers twice and the first is null, second is not null.

This does not happen for a newly created entity. In the example below the event is triggered just once and the component is not null.
```
       GameWorld.Create("Test", new Transform(), new Sprite());
```

So it seems to be something related to appending components to existing Entities.

**Comment by genaray** [comment]
Thanks! 
Looks like theres a bug in the `.Add` operation, I'll look into this :) 
However since I'm currently busy with my bachelor thesis this could take several days, for now i recommend to just insert a null check. If you want, you could also look at the source to fix the issue yourself and PR it ^^

**Comment by genaray** [comment]
Should be fixed now :) Lemme know if it works.

**Comment by akderebur** [comment]
Both the events and the command buffer seem to be working perfectly fine for my use cases. Thank you.
