### ISSUE TITLE
[Feature request] Nuget package is missing .pdb debug symbols

### ISSUE THREAD

**Issue by clibequilibrium** [genaray/Arch#127]
It would be good to have pdb symbols bundled within NuGet package so the end user can effectively debug exceptions, assertions that happen sometimes when library is misused.

Currently in order to troubleshoot an issue with Arch the user has to install Arch from sources. 

Including .pdb symbols with the package would allow for better and effective debugging. 

This request applies not just for Arch but Arch.Extended packages

**Comment by genaray** [comment]
d923c462a6152026f4275a130ac46938a7961d0c integrates symbols for the Arch-Package.
Version `1.2.6` will soon be available as a nugget. The other packages will now follow one by one :)

**Comment by clibequilibrium** [comment]
> d923c462a6152026f4275a130ac46938a7961d0c integrates symbols for the Arch-Package.
> 
> Version `1.2.6` will soon be available as a nugget. The other packages will now follow one by one :) 

Thank you !!

**Comment by genaray** [comment]
Recently updated all arch related packages, all should feature symbols now for easier insight :)
