### ISSUE TITLE
Attempting to use an array inside of a component causes a marshalling error

### ISSUE THREAD

**Issue by 990xan** [genaray/Arch#128]
See above, attempting to make a query on a component which contains an array of (seemingly) any type, or adding a component which contains an array to an entity will cause the error:

An unhandled exception of type 'System.TypeInitializationException' occurred in Arch.dll: 'The type initializer for 'Arch.Core.Utils.Group`2' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.ArgumentException : Type 'TileGame.TestComp' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.
   at System.Runtime.InteropServices.Marshal.SizeOfHelper(Type t, Boolean throwIfNotMarshalable)
   at Arch.Core.Utils.ComponentRegistry.Add(Type type)
   at Arch.Core.Utils.ComponentRegistry.Add[T]()
   at Arch.Core.Utils.Component`1..cctor()
   
   I have tried this with a 3D array of my own type (which contains a raylib-cs Texture2D and two integers), as well as a 1D array of previous type, as well as a 1D array of integers, both of defined and undefined length. I am unsure what is causing this error. The error occurs at runtime.

Quick edit, I've noticed something strange, if I put a type _which contains_ an array into a component, no issues arise.

**Comment by genaray** [comment]
This is actually not a bug. Its C# fault... since C# sucks at determining the sizes of types with the marshal tools. Unfortunately their are the only API usable for this kind of task.

However you can manually register the component to bypass the issue : https://github.com/genaray/Arch/wiki/Utility-Features#manual-component-registration

**Comment by 990xan** [comment]
> This is actually not a bug. Its C# fault... since C# sucks at determining the sizes of types with the marshal tools. Unfortunately their are the only API usable for this kind of task.
> 
> However you can manually register the component to bypass the issue : https://github.com/genaray/Arch/wiki/Utility-Features#manual-component-registration

How do I determine the size to register the component as?

**Comment by genaray** [comment]
> How do I determine the size to register the component as?

Well research the sizes of datatypes you use :) 
E.g. : 
```csharp
struct MyArray{
   byte one,
   byte two
}
```

Is 2 bytes sized. If you use arrays inside a struct they count as a reference to an object. That pointer size depends on the architecture but can be determined via `IntPtr.Size`.
