### ISSUE TITLE
Component destructor/finalizer?

### ISSUE THREAD

**Issue by 990xan** [genaray/Arch#129]
It would be very useful to have a way to call a function on a component to be destroyed, as finalizers do not work on structs. For reference to what I'm trying to do, I am using Arch with Godot and it's rendering server, and it suggests calling a method once I am done with an RID (A handle to a thing the server uses) to dispose of it, but I am unsure how to best do that with an RID stored in a component.

**Comment by genaray** [comment]
Thats probably to specific to become a new feature. Furthermore components should not hold logic, therefore its kinda a code smell to implement such behaviour. But there several approaches to this.

1. Store a bool in that component, Set it to true, Query to dispose components where bool is true.

2. Fire an Event once you are done, intercept the event to handle the disposal somewhere else.

3. Just dispose the component manually.
