### ISSUE TITLE
Exclusive Queries

### ISSUE THREAD

**Issue by MindSwipe** [genaray/Arch#14]
Add a way to query for Entities that contain an exact match of components, so say we execute a Query with Exclusive = { Transform, Roation } in a world with an Entity (A) with components Transform and Rotation and another Entity (B) with Transform, Rotation and Ai, only Entity A would be returned.

Initially proposed in a comment on the [Share your ideas and wishes](https://github.com/genaray/Arch/discussions/8#discussioncomment-4189452) discussion

**Comment by genaray** [comment]
Here we are :) 

So what did you had in mind regarding the API ? 
I think it would make the most sense to include this in the `QueryDescription`, next to `All, Any, None`.

The usage then would look like this : 
```csharp
var desc = new QueryDescription{ Exclusive = new []{ typeof(Transform); } }
world.Query(in desc, ...);
```

**Comment by MindSwipe** [comment]
Yup, that's exactly what I was thinking of as well.

How should we handle situations like the following

```csharp
var query = new QueryDescription
{
    All = new[] { typeof(Transform), typeof(Rotation) },
    Exclusive = new[] { typeof(Rotation) }
};
```

I think we should just say that a Query with `Exclusive` set cannot have any other filter set.

Also, I think a more fitting name may be "Exact Queries", since the idea is that this query would return entities that hold exactly these components and no other components. Any input on that?

**Comment by genaray** [comment]
Perfect ^^ I would actually say that Exclusive should always have the highest priority when being set. So in such a case as..

```csharp
var query = new QueryDescription
{
    All = new[] { typeof(Transform), typeof(Rotation) },
    Exclusive = new[] { typeof(Rotation) }
};
```

The underlaying query and world would simply ignore the `All` and just go for `Exclusive` since its a smaller subset of entities. 
So yeah, pretty much what you said :D We could either just ignore `All, Any, None` in that case, or we throw an exception to enforce clarity. 

Could you clarify the `Exact Queries` ? ^^ If the intention is to create a alternative to the `QueryDescription` which is named `ExactQuery` with just one Attribute... this would work of course, but it would me incredible much work since all the existing world overloads just accept a `QueryDescription` :D

**Comment by MindSwipe** [comment]
Yup, that's along the lines of what I was thinking as well, I'd probably prefer to throw an exception, or maybe use debug assertions to gain a probably very negligible performance increase.

No, the `QueryDescription` would remain and I'd just extend that, but I think just referring to these types of `QueryDescription`s as `Exclusive Queries` is kinda vague, where as an `Exact Query` is more obvious that it will return entities with *exact*ly those components

**Comment by genaray** [comment]
Debug assertions are probably even the better way ^^ 
Ahhh alright, i missunderstood that. Thats totally fine however, so i guess its a go :D

**Comment by MindSwipe** [comment]
Sorry it took me so long to get around to this, I caught covid and was knocked out for a week.

Btw, I noticed that (at least on my machine) if I run `WorldTest.Reserve` solo it works, but if I run all the tests in `WorldTest` the Reserve test ends up red, this was fixed by changing `OneTimeSetUp` and `OneTimeTearDown` to `SetUp` and `TearDown` respectfully

**Comment by genaray** [comment]
> Sorry it took me so long to get around to this, I caught covid and was knocked out for a week.
> 
> Btw, I noticed that (at least on my machine) if I run `WorldTest.Reserve` solo it works, but if I run all the tests in `WorldTest` the Reserve test ends up red, this was fixed by changing `OneTimeSetUp` and `OneTimeTearDown` to `SetUp` and `TearDown` respectfully

Its all fine, hope you are fit again :D 
Im gonna look and merge the PR in a sec ^^
