### ISSUE TITLE
Unpredictable Archetype changing while iterating a query

### ISSUE THREAD

**Issue by RagnarGothur** [genaray/Arch#147]
**Environment:** 
* Windows 11.
* .NET 6.
* Arch 1.2.6 (nuget).

I have a complex game logic with multiple entities changing their archetypes on the fly. I have many queries in which I call Entity.Add() and Entity.Remove() for different entities on different frames. But it seems like Entity.Add() and Entity.Remove() causing changing archetype of other entities or conflicting with each other so the resulting archetype is unpredictable.

When I have a single entity I never got the bug regardless of components count.

**I reproduced the bug in example repo: https://github.com/RagnarGothur/Arch.Archetype.Issue1 so you can download and run it.**

**Comment by genaray** [comment]
Thanks! :) But this actually intended behaviour, also was an topic today in the discord server.

Theres also now a hint on the wiki:
https://github.com/genaray/Arch/wiki/Quickstart#system-aka-query

There several ways to bypass this mechanic:
https://github.com/genaray/Arch/wiki/Utility-Features#command-buffers
