### ISSUE TITLE
Remove `in Entity` from `World.Query`, `World.InlineQuery` and `World.InlineParallelQuery`

### ISSUE THREAD

**Issue by shayded-exe** [genaray/Arch#148]
Because Entity is only 8 bytes (4 if using pure ecs), isn't it actually less efficient to pass Entity by reference because you now have to dereference a pointer instead of accessing the data directly? And if you are using pure ecs mode, then a 64bit pointer is twice the memory of a 32bit entity id.

**Comment by genaray** [comment]
> Because Entity is only 8 bytes (4 if using pure ecs), isn't it actually less efficient to pass Entity by reference because you now have to dereference a pointer instead of accessing the data directly? And if you are using pure ecs mode, then a 64bit pointer is twice the memory of a 32bit entity id.

Thats actually right. One reason why there were previous changes made to the API in total. However the World.Query API has not been updated yet :) This should be done, however.

**Comment by shayded-exe** [comment]
Awesome! :)
