### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by proc-gen** [genaray/Arch#168]
Something I noticed when upgrading to 1.2.7. We no longer use `in Entity entity`, but rather just `Entity entity`.

Ex.

```
world.Query(in query, (in Entity entity) =>
{
   // Do things
});
```

then becomes

```
world.Query(in query, (Entity entity) =>
{
   // Do things
});
```

Just wanted to make everyone aware since the old version is still in the wiki.

**Comment by genaray** [comment]
Done, thanks! :)
