### ISSUE TITLE
BitSet can cause exceptions on certain platforms

### ISSUE THREAD

**Issue by metalgearsloth** [genaray/Arch#184]
Thanks to @pjb3005 for pointing me towards the environment variables to test.

We tried testing Arch on one of our servers that doesn't have avx2 enabled but it was causing crashes on live. Running with the env var `DOTNET_EnableAVX2=0` set locally can easily reproduce the issue, at least for us.

**Comment by genaray** [comment]
Any prefered way to activate the environment variables?
Just tried it with : `Environment.SetEnvironmentVariable("DOTNET_EnableAVX2", "0");` without any luck.

Guess i also need to add a bunch of components until the simd kicks in.
