### ISSUE TITLE
World should have an IsAlive for EntityReference

### ISSUE THREAD

**Issue by metalgearsloth** [genaray/Arch#187]
So there's 2 reasons:
1. If you're on PURE_ECS it's kind of weird you call EntityReference.IsAlive(world) instead of the expected World.IsAlive(EntityReference)
2. If you call World.IsAlive(EntityReference) it gets cast and becomes World.IsAlive(Entity) which if you don't realise can cause hidden bugs.

**Comment by genaray** [comment]
Resolved in 210f5282342d7b2c31b2a9331aa01c5c00c88b85
