### ISSUE TITLE
Bug in JobScheduler makes Arch not close all job threads.

### ISSUE THREAD

**Issue by Epicguru** [genaray/Arch#197]
This is actually an issue in the version of ZeroAllocJobScheduler that is currently being used in Arch.
As far as I can tell this has been fixed in more recent versions of that library.

Currently when the JobScheduler is disposed, it notifies a cancellation token and disposes a `ManualResetEvent`.
This does not correctly cause the worker thread to exit.

![image](https://github.com/genaray/Arch/assets/26253331/9704d003-0fde-4e8d-8ed6-a401f5fcf61f)
The worker thread is stuck waiting on line 53 above. Calling Dispose on the MRE does **not** stop waiting (tested on .net 8.0 but I don't think this has changed recently). Of course because the thread is stuck waiting, the cancellation token does nothing.

In my project this caused my game to not close properly, and for unit tests to run indefinitely.

I am leaving this issue here to let other people know that they should fork and fix until the new version of ZeroAllocJobScheduler has been put in to Arch.

**Comment by genaray** [comment]
Thanks!
Soon the new version will be introduced which should then fix this issue :)

**Comment by genaray** [comment]
Should be fixed since 878381fae92a27b62b150b5ba590a08586cac502.
Otherwhise reopen the issue ^^
