### ISSUE TITLE
chunk.Has<T>() is possibly broken

### ISSUE THREAD

**Issue by purrplingcat** [genaray/Arch#203]
Hi.

I was testing your ECS framework and it looks great. But I found some weird behavior about Chunk.Has<T>() which returns me false for a component which has not been registered as first. I see all my components in chunk, but is I check chunk.Has<Velocity>() it returns false, for chunk.Has<Position>() it returns true.

<img width="939" alt="image" src="https://github.com/genaray/Arch/assets/4710267/26c07084-3ad1-4456-b005-45e510e2a5d6">

Is this a bug or I did something wrong?

Thanks.

**Comment by genaray** [comment]
Thanks! Can you eloborate further, what exactly did you do? And is there a way to replicate this? ^^

**Comment by genaray** [comment]
And? ^^
