### ISSUE TITLE
Disable entity?

### ISSUE THREAD

**Issue by adjourn** [genaray/Arch#206]
Is this feature something worth considering in your opinion?

I've looked around searching for the best ECS to use and noticed that multiple others have this feature.
For example [Friflo](https://github.com/friflo/Friflo.Json.Fliox/blob/main/Engine/README.md#entity) has `entity.Enabled` which strikes me as a pretty convenient feature.

Feature could be replicated with "disabled" tag (and basically all queries excluding it) but I guess the question here is: would the "disabled" feature implementation be something more fancy and performant?

**Comment by genaray** [comment]
Arch itself does not offer a way to do this, nor will it. If you want to disable an entity, you can simply mark it yourself. However, you can always add this mechanic yourself as arch is very extensible :)
