### ISSUE TITLE
Faster version "World.Get<T>(Entity entity)"

### ISSUE THREAD

**Issue by leveljiujiu** [genaray/Arch#209]
The new version is 30% faster than the original.
```
    public ref T Get<T>(Entity entity)
    {
        ref var slots = ref EntityInfo.EntitySlots[entity.Id];
        ref var slot = ref slots.Slot;
        return ref slots.Archetype.Chunks[slot.ChunkIndex].GetArray<T>()[slot.Index];
    }
```

**Comment by leveljiujiu** [comment]
Unity2022.3.20f1
![3A2C16E1-092E-4eac-9E76-C385F1584EE6](https://github.com/genaray/Arch/assets/8155843/c2290c43-28d3-48c6-859c-2fa4f3b72354)

**Comment by genaray** [comment]
Can you create an official benchmark in arch to verify this for the repo?

**Comment by leveljiujiu** [comment]
Sorry. My bad. This difference only exists in Unity, they are not different in the benchmark.
