### ISSUE TITLE
Posibility of ordering the entities in querys based on value in a component

### ISSUE THREAD

**Issue by insanebytes** [genaray/Arch#227]
I think will be very usefull to add the posibility to order entities in querys based on a value of a component. :)

**Comment by genaray** [comment]
Thanks! #48 already discussed this topic. It's possible, but not in a query since that one defeats the purpose of an ECS. If you wanna order/sort entities I recommend to use methods like `world.GetEntities()` to fill a list and to the ordering yourself ^^

**Comment by insanebytes** [comment]
Thank you!!!!
