### ISSUE TITLE
Custom Entity??

### ISSUE THREAD

**Issue by insanebytes** [genaray/Arch#228]
Actually is possible to define a custom entity??

**Comment by genaray** [comment]
Unfortunately this is not possible (well it's possible but it does not make sense in this architecture). An entity and its id is just a row inside an array. E.g. `Entity(ID = 1000)` is pointing towards the 1000th row inside the `EntityInfo` storage where its data is stored. Entity ids are incremented and recycled regularly. Creating your own entities with your own ID would interfere with this and mess up the whole system. However, you can create a custom entity using the `DangerousExtensions`, but this only creates the entity struct and not the entity in the system. So it can only be used for a few purposes.

**Comment by insanebytes** [comment]
Ah okey, this question was provided in order to set in entities custom shortcuts to a common components. Thank you for your support! ^^
