### ISSUE TITLE
Plugins and Application root

### ISSUE THREAD

**Issue by Shadowblitz16** [genaray/Arch#234]
Bevy has something called plugins which go something like this...

```cs
var app = new Application();
app.AddPlugin(MyPlugin);
app.Run();

public void MyPlugin(Application app)
{
    app.AddSystem(...);
}


```

**Comment by genaray** [comment]
What's their purpose?

**Comment by Shadowblitz16** [comment]
@genaray plugins allow people to add systems and other plugins to the world.

**Comment by Epicguru** [comment]
This seems trivial to add using extension methods and a couple of interfaces, I don't think that this needs to be part of the core library.

**Comment by Shadowblitz16** [comment]
ok
