### ISSUE TITLE
Empty structs / Tag components should not consume any memory 

### ISSUE THREAD

**Issue by genaray** [genaray/Arch#29]
Tag components ( Empty structs ) do actually consume 1 byte per instance and are actually being allocated in each chunk.
Instead we could just ignore them, however this means that that some query like this...

```csharp
world.Query(in desc, (ref Transform t, ref SomeTag tag) => {});
```

Would throw an exception since the entity is tagged with it, but since its a non allocated tag component it can not be acessed.
`Debug.Assert` could probably help here to avoid such errors.

**Comment by clibequilibrium** [comment]
> Tag components ( Empty structs ) do actually consume 1 byte per instance and are actually being allocated in each chunk. Instead we could just ignore them, however this means that that some query like this...
> 
> ```cs
> world.Query(in desc, (ref Transform t, ref SomeTag tag) => {});
> ```
> 
> Would throw an exception since the entity is tagged with it, but since its a non allocated tag component it can not be acessed. `Debug.Assert` could probably help here to avoid such errors.

flecs enforces Tags to have at least 1 field for example, `int dummy;` and it worked quite well for them. I see no issue with that either
