### ISSUE TITLE
Ref iterators for `Query`

### ISSUE THREAD

**Issue by genaray** [genaray/Arch#39]
Would be neat to have one more alternative to the existing query APIs. A iterator directly received from the query, replacing `world.Query(in, (...) => {});`

Like this : 
```csharp
var query = world.Query(in desc); 
foreach(var refs in query.GetIterator<Position, Velocity,...>()){
   refs.t0.x += refs.t1.x;
   refs.t0.y += refs.t1.y;
}

foreach(var refs in query.GetEntityIterator<Position, Velocity,...>()){
   Console.WriteLine(refs.entity);
   refs.t0.x += refs.t1.x;
   refs.t0.y += refs.t1.y;
}
```

Those could probably even replace `world.Query(in, (...) => {})` calls completly, since they offer more advantages. They will not closure copy, offer greater controll over the iteration flow and are probably easier to maintain. 

@andreakarasho Probably already had a first draft of this according to #35 ( if i understood that correctly ) ^^

**Comment by andreakarasho** [comment]
Not really, I had a moc using the `Entities` array into `Chunk` struct, so not the real target

**Comment by genaray** [comment]
## Update

The first variants already work on my local branch... i think it would make sense to actually add deconstructors to reference types... this way it could even be optimized like this : 

```csharp
foreach(var (pos, velocity) in query.GetEntityIterator<Position, Velocity,...>()){  <-- Deconstruction happening here, makes it more readable. 
   Console.WriteLine(refs.entity);
   pos.t0.x += velocity.t1.x;
   pos.t0.y += velocity.t1.y;
}
```

**Comment by genaray** [comment]
## Update

I did some benchmarking and profiling. Its slower than the current delegate, inline, manual approach.
This is actually a terrible way of performing queries. 

Each enumerator movenext a new struct is being created and returned, pollutes the stack. Furthermore enumerators do not inline well, even when being forced. 

An better alternative is probably : 
```csharp
foreach(var (positions, velocities) in world.Query().GetChunkArrayIterator()){}
```

Probably the existing solution could also be optimized with storing a ref struct and reusing it ?
