### ISSUE TITLE
Make the World class IDisposable

### ISSUE THREAD

**Issue by solonrice** [genaray/Arch#45]
Looks like whenever a new World is created it is added to the World.Worlds static list (among many other things). Then, when calling `Destroy()`, it is removed from that list. Seems like this should happen with an IDisposable interface as well, so that there is a common way for this to occur (and convenient with `using` statement). Perhaps Entity should also have this method of disposable as well.

**Comment by genaray** [comment]
Added this in [5ab4d5b](https://github.com/genaray/Arch/commit/5ab4d5b5e6e5bfef204aa35676cb056205f87d09) :) 
`Entity` should stay as it is, making it disposable is actually a code smell since it's only an index/row/key and has nothing to dispose ^^
