### ISSUE TITLE
Why was the class-type component removed?

### ISSUE THREAD

**Issue by HiWill** [genaray/Arch#50]
Why was the class-type component removed?

**Comment by genaray** [comment]
> Why was the class-type component removed?

What do you mean exactly ? 
You can use classes as components, however that requires the latest fork. 

Its not released as a nuget package yet, but ill do this tomorrow since there were some improvements :)

**Comment by HiWill** [comment]
I saw support for class type components on the master before, but today I found that it has been restored！

**Comment by genaray** [comment]
Damn i see what you mean, it must have been overriden. I think it happened during the time of the codestyle PR. 

Im gonna fix this later, if you are using your own clone/fork you can quickly copy this commit to make it work for classes again : 

https://github.com/genaray/Arch/commit/683ee440f6244f498832744caa5bd91dfd502120

Its an quite easy fix :) however im gonna fix this later today, once im home.
