### ISSUE TITLE
Entity.Null.IsAlive() throws instead of returns false

### ISSUE THREAD

**Issue by RoyAwesome** [genaray/Arch#52]
This surprised me.  It threw an index out of range exception, which I would have expected to just return false.

**Comment by genaray** [comment]
However, this makes sense... a null entity does not exist. Thus no entity operation can be performed on it. It should only be used for comparison purposes.

Imagine you call an operation on a null class ^^ This is correct behavior in this case.

**Comment by RoyAwesome** [comment]
What would be the intended way of checking if an entity even exists before trying to do operations on it then?

**Comment by genaray** [comment]
> What would be the intended way of checking if an entity even exists before trying to do operations on it then?

```csharp
var entity = world.Create(...);
if(entity.IsAlive())
   entity.Set(...);
```

`Entity.Null` is just for comparison : 
```csharp
if(myEntity != Entity.Null && myEntity.IsAlive())
   myEntity.Set(...);
```

Ahhh i see what the real problem here is. I will adjust the API so it is clearer. To check if an entity exists you currently have to call both to verify, I will change that.
