### ISSUE TITLE
Source generator does not properly build outside windows

### ISSUE THREAD

**Issue by Pheubel** [genaray/Arch#55]
C# 11 added [raw string literals](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#raw-string-literals) and although they would be a perfect fit for source generators, it seems that due to source generators needing to be compatible with .net standard 2.0 it causes weird behavior.

When compiling from visual studio on my pc, it works like a charm. however, when building from linux or a windows workflow through github, it makes mistakes in the string literal.

The terminal gets filled with errors that look like:
`Error: /home/runner/work/Arch/Arch/src/Arch/Arch.SourceGen/Arch.SourceGen.QueryGenerator/Acessors.g.cs(7974,86): error CS1026: ) expected [/home/runner/work/Arch/Arch/src/Arch/Arch.csproj::TargetFramework=netstandard2.1]`

As a test i decided to change [`StructuralChangesExtensions.AppendWorldAdd(this StringBuilder, int)`](https://github.com/genaray/Arch/blob/master/src/Arch.SourceGen/Fundamentals/StructuralChangesExtensions.cs#L35)

```cs
var template =
    $$"""
    [SkipLocalsInit]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Add<{{generics}}>(in Entity entity, {{parameters}})
    {
        var oldArchetype = EntityInfo[entity.Id].Archetype;
        // Create a stack array with all component we now search an archetype for.
        Span<int> ids = stackalloc int[oldArchetype.Types.Length + {{amount + 1}}];
        oldArchetype.Types.WriteComponentIds(ids);
        {{setIds}}
        if (!TryGetArchetype(ids, out var newArchetype))
            newArchetype = GetOrCreate(oldArchetype.Types.Add({{types}}));
        Move(in entity, oldArchetype, newArchetype, out var newSlot);
        newArchetype.Set<{{generics}}>(ref newSlot, {{inParameters}});
    }
    """;
```

to

```cs
string template = string.Format(
@"[SkipLocalsInit]
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public void Add<{0}>(in Entity entity, {1})
{
    var oldArchetype = EntityInfo[entity.Id].Archetype;
    // Create a stack array with all component we now search an archetype for.
    Span<int> ids = stackalloc int[oldArchetype.Types.Length + {2}];
    oldArchetype.Types.WriteComponentIds(ids);
    {3}

    if (!TryGetArchetype(ids, out var newArchetype))
        newArchetype = GetOrCreate(oldArchetype.Types.Add({4}));
    Move(in entity, oldArchetype, newArchetype, out var newSlot);
    newArchetype.Set<{0}>(ref newSlot, {5});
}", generics, parameters, amount + 1, setIds, types, inParameters);
```

As a result the errors that looked like the one i described earlier went away.

# Edit
the actual issue was due to the stringbuilder being trimmed too far on Linux due to a different newline standard.

For any future souls getting haunted by source generators, temporarily adding
```
<PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
</PropertyGroup>
```
to your project might help with debugging the code that gets generated. that way you can a view into what actually gets generated.

**Comment by genaray** [comment]
Well this one is weird... im gonna do some investigation.
As far as i know that should be totally supported by linux though.

**Comment by Pheubel** [comment]
i cracked my head against this issue for a bit, but so far i am not much wiser. i changed everything around a bit to see if string format would magically solve it, however after all was changed, the old error came back again. so it is a weird

**Comment by genaray** [comment]
As far as i know c# linux support is still quite new... probably we are running into a compatibility issue or bug.
However i did some research today and could not find such a registered bug :/ 

Im gonna setup my linux machine later, probably its a stupid mistake somewhere. Just out of curiosity, your linux machine has the latest .Net installed ? ^^ Just making sure we do not miss anything here.
