### ISSUE TITLE
Entity pointing to re-used entry

### ISSUE THREAD

**Issue by stgeorge** [genaray/Arch#56]
I might be doing this wrong, as I was keeping references to an Entity in a component. 

It had an id of 100, then that entity got killed and its entry (100) was reused by some other kind of entity with a new Id (5000). So then it fails hilariously as IsAlive() is now true and has a different set of components.

So I was expecting that entity's IsAlive() to return false since that id no longer exists...

I'm ok with just keeping the entity id, but doesn't seem like there's an easy way to get an entity (or null) by entity Id from World?

**Comment by genaray** [comment]
Investigating, could you show your code real quick ? Probably theres some bug with the versions of entitys ^^

**Comment by genaray** [comment]
Alright found the issue, version recycling did not work as expected. Working on a fix rn.

**Comment by stgeorge** [comment]
Looks like you figured it out already but I'll document for completeness:

```
public struct TargetComponent  { public Entity Target; }
```

and then another query for entities with TargetComponent would check if the target is alive or not before getting a couple of components from that target.

 ```
_world.Query(in _query, (ref TargetComponent target, ref PositionComponent position) =>
{
    if (target.Entity.IsAlive()) return;
    var follow = target.Entity.Get<PositionComponent, SizeComponent>();
    ...
}
```

"target" should only ever be certain types of entities with both of those components, but was getting a totally unexpected entity missing SizeComponent.

I'm working on a bullet hell type of game, so lots of entities being created/deleted quickly.

**Comment by genaray** [comment]
Thanks ! :) 

I already have a fix for this on my local machine. However our internet connection is gone rn, guess the provider fucked up again. 

Gonna push and release the fix once its back. Since the version is not part of the entity ( to save memory and make more entities fit into an chunk ), i added a EntityReference struct which purpose is now to link between entities. Tested it locally and its working fine :)

**Comment by genaray** [comment]
Just pushed it, im gonna build the nuget in a sec :) 

The usage is quite easy and its basically : "Pay as you use".
```csharp
using var world = World.Create();

var entity = world .Create(_entityGroup);
var reference = world .Reference(entity);  // This should be stored in your component

if(reference.IsAlive())           // Checks if the entity id AND the version are still the same ( to prevent the replacement issue you had )
    reference.Entity.Get(...);
```

I decided not to put the version in the entity struct, because this would also consume memory for entities whose version you never need :)

**Comment by genaray** [comment]
1.1.5 is now available and fixes this, thanks again and sorry ! :) 
If there more problems let me know or reopen this issue ^^ 

[Release](https://github.com/genaray/Arch/releases/tag/1.1.5)
