### ISSUE TITLE
Exception when adding component to entity in query

### ISSUE THREAD

**Issue by stgeorge** [genaray/Arch#59]
For reasons I'm not sure of, when adding a component to an entity within a query. It seems to run into this problem (when processing a lot of entities, it doesn't seem to happen when there's not a lot going on):

in Archetype.cs:
```
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    [Pure]
    internal int Transfer(int index, ref Chunk chunk)
    {
        // Get last entity
        var lastIndex = chunk.Size - 1;
        var lastEntity = chunk.Entities[lastIndex];
```
        
chunk.Size is 0, so it tries to access lastIndex = -1.

So I'm not sure if it is because the chunk being transferred into might be empty once in a while? Not sure if it makes sense, but thought I'd post it in case you knew the cause, I can not find a clear way to repro it unfortunately without just throwing a ton of entities and adding components within the query (I use mostly inline non-parallel, but in this case, it happened with both parallel or non-parallel).

**Comment by genaray** [comment]
Thanks ! :) 
Im gonna investigate and fix this, looks like a logical issue.

**Comment by genaray** [comment]
Currently working on this issue, are you using the latest version ( 1.1.6 ? ) ^^ 
Just to make sure.

**Comment by stgeorge** [comment]
Yes, using latest released version.

**Comment by genaray** [comment]
> Yes, using latest released version.

Alright, just making sure since there was a 1.1.6 release which is not listed under the official github releases. It was a small additional patch not really worth mentioning ^^ 

Could you probably describe in which order you add/remove components to your entities which then results in the error ? And how long does it take, is it instant ? :) 

I just added a few add component and remove component queries to the sample and those are working fine, however I just add one component and remove on basically.

**Comment by stgeorge** [comment]
Ok, to add some context, I have a lot of "monster" entities which when killed will create a "soul" entity and those monster entities get removed. This new entity initially is missing a TargetComponent. The PlayerComponent will scan a radius for nearby "souls" and add a TargetComponent to them. Then if the soul has a TargetComponent component, it will move towards the player and when it is close enough, that entity gets removed.

When I have a low number of monsters (100) it probably never happens or would take a long time. When I cranked it up to 2000 entities, and plowed through them quickly (lots of deaths, lots of souls, lots of mass collecting) then it seems to happen at any time - sometimes it doesn't happen at all. So I think it's a rare condition. 

I don't have other systems adding/removing entities or adding components on the fly yet. As a workaround I tried adding the TargetComponent permanently and started setting a property on it instead, but in general I was thinking of using Components to track certain states, but maybe that's not a good idea?

**Comment by stgeorge** [comment]
Also, I did change all my Entity to EntityReference in the components themselves and check if they are alive before operating on an entity not part of query itself.

**Comment by genaray** [comment]
For now ( as a workaround ) you could simply assign all components once to the entity and give each one a flag to indicate whether its activated or not. 

This should still be efficient :) You simply skip entities when their component flag is set.

I did some testing and probably found the issue, not sure if its the same one. I also optimized the add/remove methods.
Im gonna do a bulk test as next to see if the add/remove operation causes anymore crashes.

**Comment by stgeorge** [comment]
I'll definitely try out any new updates with the old code.

I'll double check any parallel queries.

**Comment by stgeorge** [comment]
Dude, you are a sorcerer! I took the latest copy of your code and was able to chew through 2000... 4000.... 6000! entities before things started slowing to a crawl (couldn't get to 10k but that's due to my code, not yours) but most importantly, no crashes! I think you squashed this one. Very nice, and an unexpected perf boost is a cherry on top.

Thanks for looking into this, I think it might be case closed for my issue.

**Comment by genaray** [comment]
Thanks a lot :) and glad that it worked, im gonna release this as a nuget later.

Probably ill gonna add the query bulk operations too, this will speed up several operations aswell ^^

**Comment by genaray** [comment]
> Dude, you are a sorcerer! I took the latest copy of your code and was able to chew through 2000... 4000.... 6000! entities before things started slowing to a crawl (couldn't get to 10k but that's due to my code, not yours) but most importantly, no crashes! I think you squashed this one. Very nice, and an unexpected perf boost is a cherry on top.
> 
> Thanks for looking into this, I think it might be case closed for my issue.

The bulk operations API is nearly finished and will boost the performance of adding/removing or destroying entities by a whopping 1000% for certain scenarios. The first draft is on the master already and :

```csharp
world.Add(in query, someComponent);
world.Set(in query, newSomeComponentValue);
world.Remove<SomeComponent>(in query);
```

Can run for up to hundred thousand of entities EVERY single frame. This is incredible and in certain scenarios your game could also profit from this :)

**Comment by stgeorge** [comment]
Thanks for the update, I will check it out as soon as I can!
