### ISSUE TITLE
entity.Add(cmp) works differently than World.Add(entity, cmp)

### ISSUE THREAD

**Issue by stgeorge** [genaray/Arch#61]
Hey, things have been running pretty good so far with the latest changes. Found a minor one that seems to be reproducible:

entity.Add(new AbcComponent { Field = 1 });

Uses the default uninitialized AbcComponent component instead of the initialized component.

this does seem to work:

World.Add(entity, new AbcComponent { Field = 1 });

**Comment by genaray** [comment]
> Hey, things have been running pretty good so far with the latest changes. Found a minor one that seems to be reproducible:
> 
> entity.Add(new AbcComponent { Field = 1 });
> 
> Uses the default uninitialized AbcComponent component instead of the initialized component.
> 
> this does seem to work:
> 
> World.Add(entity, new AbcComponent { Field = 1 });

Thanks! Gonna investigate this :)
