### ISSUE TITLE
Query BitSet comparison issue

### ISSUE THREAD

**Issue by stgeorge** [genaray/Arch#63]
Found an issue when my component count increased past 32. It started failing on components being "found" in Chunks not containing them causing memory access errors.

In BitSet All method, when the bitset for the new component extends to 2 uint's, but it checks against a bitset with 1 uint, there is an extra check to handle bitset's 2nd uint:

        var extra = _bits.Length - count;
        for (var i = count; i < extra; i++)

Since extra is subtracting "count", and starting the loop from "count", the loop won't run and always returns true. It can use the bits.Length to loop through the extra uint.

        for (var i = count; i < _bits.Length; i++)

A unit test for it:

    [Test]
    public void AllWithDifferentLengthBitSet()
    {
        var bitSet1 = new BitSet();
        bitSet1.SetBit(5);
        var bitSet2 = new BitSet();
        bitSet2.SetBit(33);

        bool result = bitSet2.All(bitSet1);

        That(result, Is.EqualTo(false));
    }

**Comment by genaray** [comment]
Thanks! Im gonna fix this quick :)

**Comment by genaray** [comment]
Was fixed in the latest commit :)

**Comment by stgeorge** [comment]
Ah, I should mention the same issue probably exists in Any, None, Exclusive (I don't use those quite as much)
