### ISSUE TITLE
Alternative to Dictionary<T, int>

### ISSUE THREAD

**Issue by Donaut** [genaray/Arch#67]
In dotnext they created a generic class with a static read-only int field each time somebody accesses the generic class with a new type the static field is incremented. And thus creating a compile-time dictionary. [TypeMap](https://github.com/dotnet/dotNext/blob/master/src/DotNext/Collections/Specialized/ITypeMap.cs) There was a discussion about it too somewhere in the c# runtime repository but sadly I lost that.

**Comment by genaray** [comment]
Thanks! :) Haven't seen that one. I will take a look at it.

**Comment by Donaut** [comment]
Hello, I have good news :). The idea works like a charm. Below is a sample code of how it looks.

```c#
var world = new World();

// Approach 1: Builders
var builder = new ArcheTypeInfo.Builder();
builder.AddComponent<int>();
builder.AddComponent<ulong>();
var archeTypeInfo = builder.Build(); // We want to avoid creating new ArcheTypes every time so we need a way to locate already existing ArcheTypes. ArcheTypeInfo is a struct that is used as a dictionary key for locating already existing ArcheTypes.
var entity = world.CreateEntity(archeTypeInfo);

// Approach 2: Generic methods that use the builder internally.
// world.CreateEntity<T0..T9>(in T0..T9) If we dont want to use the builder approach. It's a little bit slower than the builder approach.

// Set method with multiple generics so we can quickly assign data for each component type.
entity.Set<T0..T9>(in T0..T9);
```

**Comment by genaray** [comment]
Thats great! :) 

Just some questions:
- do you have a working version somewhere? 
- Can the builder be made a struct?

However i think the .create call with generics should stay aswell since thats a nice api for quick prototyping, it also sets the values in the same step which is also quite nice :)

**Comment by genaray** [comment]
> There is no concept of ComponenTypes

Well this is a problem, i think such an approach does not exclude the concept of componenttypes however. ComponentTypes are pretty important for the underlying chunks and store meta data such as byte size and in the future if the component is managed or not ^^ But if a type can be converted to an index, it can also be converted to the componenttype with that approach i guess.
