### ISSUE TITLE
Non-github contact details/discussion area?

### ISSUE THREAD

**Issue by moonheart08** [genaray/Arch#71]
IRC, Matrix, Discord, etc?
Would be helpful for things not fit for github issuess.

**Comment by genaray** [comment]
I actually thought the discussions section would be great for this :) 

But no one uses it, so a discord might he nice.

**Comment by clibequilibrium** [comment]
+1 for discord channel , worked very well for flecs :)

**Comment by genaray** [comment]
So i quickly set up a small discord server :) 
https://discord.gg/htc8tX3NxZ

Feel free to join ^^ 
(Im excited if we can gather more than 10 people in total).
