### ISSUE TITLE
Possible reference issue?

### ISSUE THREAD

**Issue by proc-gen** [genaray/Arch#74]
I found what might be another issue due to moving archetypes.

If I make changes using `entity.Remove<>()`, it seems to change the archetype of the entity immediately, so then the refs become incorrect. The `Console.WriteLine("Hello")` should never be reached, but I hit the break point locally.

```
world.Query(in enemyQuery, (in Entity entity, ref EntityStatus entityStatus, ref SpriteSheet spriteSheet, ref Animation animation) =>
            {
                if (entityStatus.State == State.ReadyToDie)
                {
                    entityStatus.State = State.Dying;

                    if (entity.Has<Burn>())
                    {
                        entity.Remove<Burn>();
                    }
                    if (entity.Has<Slow>())
                    {
                        entity.Remove<Slow>();
                    }
                    if (entity.Has<Shock>())
                    {
                        entity.Remove<Shock>();
                    }

                    if (spriteSheet.Width == 16)
                    {
                        if(entity.Get<Health>().Current > 0)
                        {
                            Console.WriteLine("hello");
                        }
                        int bloodToUse = random.Next(1, 9);
                        spriteSheet = new SpriteSheet(textures["MiniBlood" + bloodToUse], "MiniBlood" + bloodToUse, getMiniBloodNumFrames(bloodToUse), 1, 0, .5f);
                        animation = new Animation(0, getMiniBloodNumFrames(bloodToUse) - 1, 1 / 60f, 1, false);
                    }
                    else
                    {
                        int bloodToUse = random.Next(1, 5);
                        spriteSheet = new SpriteSheet(textures["Blood" + bloodToUse], "Blood" + bloodToUse, 30, 1, 0, .5f);
                        animation = new Animation(0, 29, 1 / 60f, 1, false);
                    }

                    if (entityStatus.State == State.Alive)
                    {
                        Console.WriteLine("Hello");
                    }
                }
                else if (entityStatus.State == State.Dying && animation.CurrentFrame == animation.LastFrame)
                {
                    entityStatus.State = State.Dead;
                }
            });
```

My solution for now will be to move the removal to a separate query because the sprite/animation change later in the loop is affecting enemies that haven't been killed yet. Oddly enough, I already had to do this to fix some issues in removing the physics component. 

```
world.Query(in enemyQuery, (ref EntityStatus entityStatus, ref SpriteSheet spriteSheet, ref Animation animation) =>
            {
                if (entityStatus.State == State.ReadyToDie)
                {
                    entityStatus.State = State.Dying;

                    if (spriteSheet.Width == 16)
                    {
                        int bloodToUse = random.Next(1, 9);
                        spriteSheet = new SpriteSheet(textures["MiniBlood" + bloodToUse], "MiniBlood" + bloodToUse, getMiniBloodNumFrames(bloodToUse), 1, 0, .5f);
                        animation = new Animation(0, getMiniBloodNumFrames(bloodToUse) - 1, 1 / 60f, 1, false);
                    }
                    else
                    {
                        int bloodToUse = random.Next(1, 5);
                        spriteSheet = new SpriteSheet(textures["Blood" + bloodToUse], "Blood" + bloodToUse, 30, 1, 0, .5f);
                        animation = new Animation(0, 29, 1 / 60f, 1, false);
                    }
                }
                else if (entityStatus.State == State.Dying && animation.CurrentFrame == animation.LastFrame)
                {
                    entityStatus.State = State.Dead;
                }
            });

            world.Query(in query, (in Entity entity, ref EntityStatus entityStatus, ref Body body) => 
            { 
                if(entityStatus.State != State.Alive)
                {
                    physicsWorld.DestroyBody(body);
                    entity.RemoveRange(typeof(Body), typeof(Burn), typeof(Slow), typeof(Shock));
                }
            });
```

I may also just be trying to do too much in my loops, so feel free to tell me I'm doing things a dumb way 😄 

Either way, keep of the great work on Arch!

**Comment by genaray** [comment]
Hey there! :) 

If i understand the problem correctly its basically like this? 
- Entity is ready to die, enters the large if statement
- Entity gets removed one of the components (Burn, Shock etc)
- The `Console.WriteLine("Hello");` gets entered since the entity is suddenly alive again

Correct? ^^ 
If that's the case, that's actually intended behaviour. Changing an entity structure changes the entity at exact that moment. And the entity is being removed from its current slot and gets moved to another archetype. The previous slot is being filled with another entity to ensure tight packed arrays. And therefore the passed refs change. 

Such behaviour basically acts as some sort of "synchronisation" point and should be handled with care. You either have two options :) 
- Do structural changes at the end of the lambda, that way you wont mess up the refs.
- Use the `CommandBuffer` to buffer and playback those changes at a later point. (However the recent nuget has a small bug with that one, the master fixed it).
- Create defensive copies of components and entities in the lambda, but that would make the code less readable.
- Or just separate the queries to ensure like a `one query = one purpose` doctrine.

Other ECS frameworks buffer such operations during a query to play them back after the query is finished. However, that brings many new problems and an awful speed.
I actually think that the way you solved it, is the most elegant way. And probably even the most readable :> 

And thanks a lot! I hope its clearer now ^^ 
Im gonna mention that somewhere in the wiki soon :)

**Comment by proc-gen** [comment]
Makes sense! My last foray into using an ECS was with https://github.com/PeteyChan/SimpleECS, which I had to pull the project source in to even use it on my own project. That one did buffer the operations and I was kind of used to that.

I'll try that update for `entity.Remove`. I was still having issues with the individual `entity.Has` followed by `entity.Remove` for each component type. Essentially, the enemies would die and still be on screen, though I didn't dig into why and that's when I moved to `entity.RemoveRange`.

**Comment by genaray** [comment]
> I'll try that update for `entity.Remove`. I was still having issues with the individual `entity.Has` followed by `entity.Remove` for each component type. Essentially, the enemies would die and still be on screen, though I didn't dig into why and that's when I moved to `entity.RemoveRange`.

Thats actually interesting aswell. If that persists with the latest 1.2.3 non beta version... Please tell me in that case ^^ i actually need every bug report i can get to fix all remaining bugs once and for all :D

Im actually using arch in my gameserver and its working fine rn. But everyone uses stuff differently so im probably avoiding such a bug by acciddent :) 

So would be great if you could try that out and report hack here :)

**Comment by proc-gen** [comment]
It was me making the same mistake after moving it from one query to another. If I had put the if statements after removing the Body, it likely would have worked just fine.

This is what I had before the `RemoveRange`. (Switching to Remove<> worked!)

```
world.Query(in query, (in Entity entity, ref EntityStatus entityStatus, ref Body body) => 
            { 
                if(entityStatus.State != State.Alive)
                {
                    if (entity.Has<Burn>())
                    {
                        entity.Remove<Burn>();
                    }
                    if (entity.Has<Slow>())
                    {
                        entity.Remove<Slow>();
                    }
                    if (entity.Has<Shock>())
                    {
                        entity.Remove<Shock>();
                    }

                    physicsWorld.DestroyBody(body);
                    entity.Remove<Body>();
                }
            });
```

**Comment by genaray** [comment]
Glad to hear! :D 
Yeah it actually takes time to understand whats exactly going on behind the scenes, but once understood it will be worth it. Its like a high risk/high reward scenario ^^ 

If there any other issues, lemme know! :)
