### ISSUE TITLE
How can I make a sorted query ?

### ISSUE THREAD

**Issue by Gray-SS** [genaray/Arch#86]
I would like to know how to make a sorted query ? I have no clue how to do this. I would like to draw a list of entities sorted by a 'zIndex' value contained in a 'RenderInfo' component. Is this possible ?

**Comment by genaray** [comment]
Great question! :) Well... this is normally something that you (or the rendersystem) needs to do ^^
But its kinda easy... like this: 

```csharp
world.GetEntities(in queryDescription, someSpanOrList);  // Get all entities you need, like all with Sprites or whatever:
someSpanOrList.Sort(...);
foreach(var entity in someSpanOrList){
   Render....
}
```

**Comment by Gray-SS** [comment]
Ohhh thanks, it was that simple. Thank you for responding so quickly!
