### ISSUE TITLE
Entity creation and add of components while iterating a query

### ISSUE THREAD

**Issue by clibequilibrium** [genaray/Arch#87]
Hello !

I am seeing some weird artifacts in my project when trying to create entities when iterating a query or during system initialization.  
In a recent 1.2.4 update  adding 2 components in a row is ignored 

```CSharp
 var entity = World.Create();

 entity.Add(skyData); // this gets ignored and the final entity only has Sun component
 entity.Add(sun);
```

But this works. 

```CSharp
entity.Add(skyData, sun)
```

I tried to reproduce it on a clean project with test components and was not able to , so it seems like it's really specific to my project.
My 2 questions would be, is is advised to prefer Command buffers for entity adding, deletion operations while iterating a query, and should we just discourage such operations and assert if a user tries to create an entity directly during iteration? 

Do you happen to know why creating ~40 entities in one frame might invalidate first ~10 of them and they are basically getting erased? I don't use multi-threading so I don't assume there could be any race conditions ?

Sorry for messy format for an issue :P

**Comment by genaray** [comment]
First of all, thanks for reporting! :) 

Im gonna check this immediately, looks like some "new" bug was introduced.
Could you test the 1.2.4.2-beta? Thats the latest preview which had some improvements and bug fixes meanwhile, i hope that's solved in the latest version :)

**Comment by clibequilibrium** [comment]
> First of all, thanks for reporting! :)
> 
> Im gonna check this immediately, looks like some "new" bug was introduced. Could you test the 1.2.4.2-beta? Thats the latest preview which had some improvements and bug fixes meanwhile, i hope that's solved in the latest version :)
> 
> Iterating and creating entities should never be a problem. CommandBuffers only make sense for multithreading, that's their main purpose. Or to schedule structural changes ^^

I will get back to you on this with a repro if I can. Thank you !

**Comment by genaray** [comment]
> I will get back to you on this with a repro if I can. Thank you !

Perfect, but for now just test if the 1.2.4.2-beta produces the same error ^^ 
Would be great if you could tell me later :D

**Comment by genaray** [comment]
Hmmm dammit, than its an undiscovered bug. Is your project open source? I could help with debugging to speed up things.

Since each `.Add` operation triggers a structural change which results in the copying an entity from one to another archetype, i would assume that for some reason it just picks the wrong archetype for SkyData. And therefore the entity does not have it... still weird since it works when the action is combined. 

Do you register components yourself somewhere with `ComponentRegistry.Add()` ?

Yes we can close this for now, In the meantime i will add some tests to check some stuff.

**Comment by clibequilibrium** [comment]
> Hmmm dammit, than its an undiscovered bug. Is your project open source? I could help with debugging to speed up things.
> 
> Since each `.Add` operation triggers a structural change which results in the copying an entity from one to another archetype, i would assume that for some reason it just picks the wrong archetype for SkyData. And therefore the entity does not have it... still weird since it works when the action is combined.
> 
> Do you register components yourself somewhere with `ComponentRegistry.Add()` ?
> 
> Yes we can close this for now, In the meantime i will add some tests to check some stuff.

It's funny you ask, it will be a C# port of https://github.com/clibequilibrium/EquilibriumEngine I can open source it but it has a backend involved so you might need to sign up to http://login.playequilibrium.cloud/, unless I can create a no login branch for you. Your call 😁 

> Do you register components yourself somewhere with ComponentRegistry.Add() ?

No not really but my structs look like that


```CSharp

public struct Sun
{
    public Vector3 NorthDir;
    public Vector3 SunDir;
    public Vector3 UpDir;
    public float Latitude;
    public Month Month;

    public float EclipticObliquity;
    public float Delta;
}

public struct SkyData
{
    // public VertexLayout ScreenPosVertex;

    public VertexBufferHandle Vbh;
    public IndexBufferHandle Ibh;
    public ProgramHandle SkyProgram;

    public UniformHandle USunLuminance;
    public UniformHandle USkyLuminanceXYZ;
    public UniformHandle USkyLuminance;
    public UniformHandle USunDirection;
    public UniformHandle UParameters;
    public UniformHandle UPerezCoeff;

    public float Time;
    public float TimeScale;
    public float Turbidity;
}
```

I commented vertex layout because the handle structs are looking like this

```CSharp
	public struct ProgramHandle {
	    public ushort idx;
	    public bool Valid => idx != UInt16.MaxValue;
	}
```

So nothing out of the ordinary, no managed stuff

**Comment by genaray** [comment]
> It's funny you ask, it will be a C# port of https://github.com/clibequilibrium/EquilibriumEngine
That sounds pretty cool actually! :) 

> I commented vertex layout because it had some fixed byte buffers (maybe it would cause issues)
Hmm... however, it should not result into such a behaviour. The struct size should not conflict with the entity structure in general :/

Alright thanks! ^^ This should actually be "easy" to debug. Just pull the sources into your project, set a breakpoint in the .Add method and see what exactly happens in there. My guess is that its probably a iusse with the bitset calculation which results in the wrong archetype. That during `.Add` the same archetype is being picked as it is already in or something similar.

**Comment by clibequilibrium** [comment]
Got this, I think I am onto something

![image](https://user-images.githubusercontent.com/105135724/232642994-33d37213-6e35-4617-a2e3-2befa3ca058c.png)

```CSharp
  // A common mistake, happening in many cases.
        Debug.Assert(source != destination, "From-Archetype is the same as the To-Archetype. Entities cannot move within the same archetype using this function. Probably an attempt was made to attach already existing components to the entity or to remove non-existing ones.");
```

Do you think it's possible to include pdb symbols in nuget package? So asserts are triggered if user install the library not from sources?

**Comment by clibequilibrium** [comment]
@genaray okay about my initial issue this is the callstack 

![image](https://user-images.githubusercontent.com/105135724/232644178-f7cc44ea-b38f-4f0e-9994-8ce10692a340.png)


![image](https://user-images.githubusercontent.com/105135724/232644205-2bf4176a-01ad-4462-ad67-efda2bb27cea.png)

![image](https://user-images.githubusercontent.com/105135724/232644218-2cbdbbd2-2c70-49a6-aa57-6262501d9736.png)

**Comment by clibequilibrium** [comment]
@genaray  I think there is a problem with your hashing function at CompileTimeStatics.cs 

![image](https://user-images.githubusercontent.com/105135724/232645075-bf745796-d51d-4cee-bd08-b3d51d645fe5.png)


I used the FNV1A32 from Burst Unity Compiler and not having the issue again. I think hash collision occurs and it returns the same archetype. 


```CSharp
   [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static int GetHashCode(Span<ComponentType> obj)
    {
        // From https://stackoverflow.com/a/52172541.
        unchecked
        {
            int hash = 0;
            foreach (var type in obj)
            {
                hash += GetHashCode32(type.Type);
            }

            return hash;
        }
    }
    

        /// <summary>
        /// Gets a 32-bits hashcode from a type computed for the <see cref="System.Type.AssemblyQualifiedName"/>
        /// This method cannot be used from a burst job.
        /// </summary>
        /// <param name="type">The type to compute the hash from</param>
        /// <returns>The 32-bit hashcode.</returns>
        public static int GetHashCode32(Type type)
        {
            return HashStringWithFNV1A32(type.AssemblyQualifiedName);
        }


        // method internal as it is used by the compiler directly
        internal static int HashStringWithFNV1A32(string text)
        {
            // Using http://www.isthe.com/chongo/tech/comp/fnv/index.html#FNV-1a
            // with basis and prime:
            const uint offsetBasis = 2166136261;
            const uint prime = 16777619;

            uint result = offsetBasis;
            foreach (var c in text)
            {
                result = prime * (result ^ (byte)(c & 255));
                result = prime * (result ^ (byte)(c >> 8));
            }
            return (int)result;
        }
 ```

**Comment by genaray** [comment]
Thanks a lot! :) 

Im gonna review those hash functions and will pick something else instead. Couldnt we just use FNV? If it works in your project, it will probably also work in the main repo? ^^ 

However im not sure about its speed, probably a bit slower. 

Ill do some research to see what else exists ^^

**Comment by clibequilibrium** [comment]
> Thanks a lot! :)
> 
> Im gonna review those hash functions and will pick something else instead. Couldnt we just use FNV? If it works in your project, it will probably also work in the main repo? ^^
> 
> However im not sure about its speed, probably a bit slower.
> 
> Ill do some research to see what else exists ^^

I think FNV is more for string hashing, so you could do something like 


```CSharp
  public static int GetHashCode32(Span<ComponentType> types)
    {
        var typeString = string.Empty;

        foreach (var type in types)
        {
            typeString += type.Type.AssemblyQualifiedName;
        }

        return HashStringWithFNV1A32(typeString);
    }
 ```
 
 The speed is okay of this hash function. MurmurHash will be better, but I also think you have Span<uint> you need to hash  ?

**Comment by genaray** [comment]
I actually think that this is kinda tricky. Researched a bit, Murmurhash is the "way to go" for BitSet hashing atleast.
However i have no clue yet if hashing the `List<ComponentType>` with it is possible. Since that one is not "sorted".

Possible it makes sense to convert that list to a stackalloc bitset and hash that one. That should still be performant ^^

**Comment by clibequilibrium** [comment]
> I actually think that this is kinda tricky. Researched a bit, Murmurhash is the "way to go" for BitSet hashing atleast. However i have no clue yet if hashing the `List<ComponentType>` with it is possible. Since that one is not "sorted".
> 
> Possible it makes sense to convert that list to a stackalloc bitset and hash that one. That should still be performant ^^

Hmm, can you ensure that the list of components will be sorted by their type name alphabetically or at least their ids ? So your hash function will always produce same results. Otherwise why the performance of the Add operation matters much ? it's something that happens infrequently 🤔
