### ISSUE TITLE
TryGetArchetype uses reference equality instead of SequenceEquals

### ISSUE THREAD

**Issue by MindSwipe** [genaray/Arch#9]
In the World method `TryGetArchetype(Type[], out Archetype)` the backing `PooledDictionary` uses reference equality, which leads to unexpected behavior such as this:

```csharp
var archTypes1 = new Type[] { typeof(Transform) };
var archTypes2 = new Type[] { typeof(Transform) };

var entity1 = world.Create(archTypes1);
var entity2 = world.Create(archTypes2);
```

Creating 2 Archetypes in the World as `archTypes1` and `archTypes2` don't reference the same instance of `Type[]`.

The fix is quite easy, implement an `IEqualityComparer<Type[]>` that uses `SequenceEquals` and pass it to the `PooledDictionary` to use.

**Comment by genaray** [comment]
Thanks again ! Quite easy to miss such details. Happy that someone thinks of such things :) 

On my way to fix that issue ^^

**Comment by MindSwipe** [comment]
I already have a fix ready to go. The PR also includes an amended .gitignore from https://github.com/github/gitignore/blob/main/VisualStudio.gitignore as many folders and files were automatically included on my end

**Comment by genaray** [comment]
Thanks and great work :) I will quickly create a new hotfix release and nuget for it.
