### ISSUE TITLE
New QueryDescription magically erases entities of unrelated types

### ISSUE THREAD

**Issue by clibequilibrium** [genaray/Arch#91]
Hello it's me again. 

I have 1 more issue, I have narrowed down what Arch.Extended generates for a simple Query.  
The issue I am facing if I declare

```CSharp
    private QueryDescription DrawSky_QueryDescription = new QueryDescription { All = new ComponentType[] { typeof(Equilibrium.Components.SkyData), typeof(Equilibrium.Components.Sun) }, Any = Array.Empty<ComponentType>(), None = Array.Empty<ComponentType>(), Exclusive = Array.Empty<ComponentType>() };
```

I lose all my entities in the world with a component ChatReceivedMessage. It is a very very strange issue and you can see what happens on the video. There is a simple ImGui window that takes a list of ChatReceivedMessage, if I declare such query description all my messages are gone, otherwise they exist.

I keep investigating what can be the issue, but it seems that my Sun and SkyData components are evil :P Can be related to the hash code collision 

https://user-images.githubusercontent.com/105135724/232948894-ca471c8b-f477-455e-806e-cd93b5fc82ad.mp4

I noticed it also breaks if the total component size is above 32, are we limited to 32 components by any chance?? especially in SpanBitSet

EDIT:

Yes !! it's definetely the 32 components limit, might have something to do with bitsets and maybe the amount of component bits possibilities in an archetype is limited to 1 uint , 32 bits ? It could actually explain the "fake hash collision" issue I reported earlier , because it would break exactly when I bypass the limit of 32 components and try to assign 33 and 34th to an entity

**Comment by genaray** [comment]
Investigating this, actually we shouldnt be limited to 32 components. I added tests for this some while ago :/ 

Im gonna look at that ^^

**Comment by genaray** [comment]
> ! it's definetely the 32 components limit, might have something to do with bitsets and maybe the amount of component bits possibilities in an archetype is limited to 1 uint , 32 bits ? It could actually explain the "fake hash collision" issue I reported earlier , because it would break exactly when I bypass the limit of 32 components and try to assign 33 and 34th to an entity

So i did some testing... E.g. i created following test (i did not had like 32 components structs, so i took everything i could and threw it onto the entity like this...

```csharp
  /// <summary>
    ///     Checks if the <see cref="World"/> creates <see cref="Entity"/> correctly.
    /// </summary>
    [Test]
    public void CreateBulk()
    {
        using var world = World.Create();
        var entity = world.Create(new ComponentType[] {
            typeof(int),
            typeof(long),
            typeof(double),
            typeof(char),
            typeof(string),
            typeof(object),
            typeof(StringBuilder),
            typeof(WorldTest),
            typeof(EntityTest),
            typeof(QueryTest),
            typeof(ArchetypeTest),
            typeof(BitSetTest),
            typeof(ChunkTest),
            typeof(CommandBufferTest),
            typeof(EntityInfoDictionaryTests),
            typeof(Entity),
            typeof(Archetype),
            typeof(List<int>),
            typeof(BitSet),
            typeof(JaggedArray<int>),
            typeof(List<string>),
            typeof(List<object>),
            typeof(List<long>),

            typeof(List<double>),
            typeof(List<char>),
            typeof(List<uint>),
            typeof(List<byte>),
            typeof(List<BitSet>),
            typeof(List<Entity>),
            typeof(List<Archetype>),
            typeof(List<ArchetypeTest>),
            typeof(List<CommandBufferTest>),
        });

        entity.Add(new List<EntityInfoDictionaryTests>());
    }
```

This worked, the entity had 32 components and the 33 was added successfully and its value was returned correctly :o 
Im kinda confused now. How many components do you have in total (or registered in `ComponentRegistry`?) ^^ We really need something reproceable for this. I also checked the hashes, of course there collisions but for our case the chance is extremely low. Unfortunately there no other good hashes, but i plan to rewrite the mechanic a bit in the future to remove dictionary completely and get rid of hashes.

**Comment by clibequilibrium** [comment]
> ```cs
> [Test]
>     public void CreateBulk()
>     {
>         using var world = World.Create();
>         var entity = world.Create(new ComponentType[] {
>             typeof(int),
>             typeof(long),
>             typeof(double),
>             typeof(char),
>             typeof(string),
>             typeof(object),
>             typeof(StringBuilder),
>             typeof(WorldTest),
>             typeof(EntityTest),
>             typeof(QueryTest),
>             typeof(ArchetypeTest),
>             typeof(BitSetTest),
>             typeof(ChunkTest),
>             typeof(CommandBufferTest),
>             typeof(EntityInfoDictionaryTests),
>             typeof(Entity),
>             typeof(Archetype),
>             typeof(List<int>),
>             typeof(BitSet),
>             typeof(JaggedArray<int>),
>             typeof(List<string>),
>             typeof(List<object>),
>             typeof(List<long>),
> 
>             typeof(List<double>),
>             typeof(List<char>),
>             typeof(List<uint>),
>             typeof(List<byte>),
>             typeof(List<BitSet>),
>             typeof(List<Entity>),
>             typeof(List<Archetype>),
>             typeof(List<ArchetypeTest>),
>             typeof(List<CommandBufferTest>),
>         });
> 
>         entity.Add(new List<EntityInfoDictionaryTests>());
>     }
> ```

```CSharp
[Test]
    public void CreateBulk()
    {
        using var world = World.Create();

        for (int i = 0; i < 200; i++)
        {

            var entity = world.Create(new ComponentType[] {
            typeof(int),
            typeof(long),
            typeof(double),
            typeof(char),
            typeof(string),
            typeof(object),
            typeof(StringBuilder),
            typeof(WorldTest),
            typeof(EntityTest),
            typeof(QueryTest),
            typeof(ArchetypeTest),
            typeof(BitSetTest),
            typeof(ChunkTest),
            typeof(CommandBufferTest),
            typeof(EntityInfoDictionaryTests),
            typeof(Entity),
            typeof(Archetype),
            typeof(List<int>),
            typeof(BitSet),
            typeof(JaggedArray<int>),
            typeof(List<string>),
            typeof(List<object>),
            typeof(List<long>),
            typeof(List<double>),
            typeof(List<char>),
            typeof(List<uint>),
            typeof(List<byte>),
            typeof(List<BitSet>),
            typeof(List<Entity>),
            typeof(List<Archetype>),
            typeof(List<ArchetypeTest>),
            typeof(Dictionary<int, BitSet>),
            typeof(Dictionary<bool, Entity>),
            typeof(Dictionary<string, Archetype>),
        });
        }

        var query = new QueryDescription().WithAll<Dictionary<uint, ArchetypeTest>>();

        var newEntity = world.Create(new Dictionary<uint, ArchetypeTest>());
        Console.WriteLine(world.CountEntities(q));
    }
    ```
    
    Try this, the counter will be 0 of the entity with Dictionary<uint, ArchetypeTest>

**Comment by genaray** [comment]
Inspecting once im home :)

**Comment by genaray** [comment]
Should be solved in 040877762c2e6688850a8b708a3dfcf48dc42e93 :) 

The issue is the following one. The "Any" filter caused that behaviour. The bitset of the any filter checks for compatible other bitsets by doing a `&`. If no any filter is set, all of its bits are set to 1 to always return true in the queries since ALL components are wanted.

However, once there more than 32 components... this was not accounted in the any filter. This resulted in a false and therefore the query was ignored.

Im still looking for a better implementation, the current Any check looks like this :
```csharp
    public bool Any(BitSet other)
    {
        var otherBits = other._bits;
        var count = Math.Min(_bits.Length, otherBits.Length);

        for (var i = 0; i < count; i++)
        {
            var bit = _bits[i];
            if ((bit & otherBits[i]) != 0)
            {
                return true;
            }
        }

        // Handle extra bits on our side that might just be all zero.
        var bitCount = _bits.Length;
        for (var i = count; i < bitCount; i++)
        {
            if (_bits[i] != 0)
            {
                return false;
            }
        }

        return false;
    }
```
However its late and I'm tired, so i cant find a better way of doing the any filter rn.

Would be great if you could try it out :) Your provided test runs now and the query returns 1.
I hope that this also solves the entity creation error you had. They might be linked, would be great if you could keep me updated!

**Comment by clibequilibrium** [comment]
@genaray  works like a charm !

Please take some rest, can always come back to it with the fresh set of energy . Thank you so much for this quick fix  !

**Comment by genaray** [comment]
> @genaray works like a charm !
> 
> Please take some rest, can always come back to it with the fresh set of energy . Thank you so much for this quick fix !

Sounds great, but the entity bug with the components (SkyData) still exists right? ^^

**Comment by clibequilibrium** [comment]
> 

Sadly it does. So your PR fixes the deletion of entities and 32 components limit. 
But there is still hash collision with 

```CSharp
  var entity = World.Create(new Name { Value = "SkySystemData" });
        entity.Add(skyData);
        entity.Add(sun);
```
it asserts on 

```
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void Move(Entity entity, Archetype source, Archetype destination, out Slot destinationSlot)
    {
        // A common mistake, happening in many cases.
        Debug.Assert(source != destination, "From-Archetype is the same as the To-Archetype. Entities cannot move within the same archetype using this function. Probably an attempt was made to attach already existing components to the entity or to remove non-existing ones.");


---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
From-Archetype is the same as the To-Archetype. Entities cannot move within the same archetype using this function. Probably an attempt was made to attach already existing components to the entity or to remove non-existing ones.
---- Assert Long Message ----
```

But doing 

```cs
  var entity = World.Create(skyData);
        entity.Add(sun);
        entity.Add(new Name { Value = "SkySystemData" });
```

Works... Or if using another hash function.

**Comment by genaray** [comment]
> > 
> 
> Sadly it does. So your PR fixes the deletion of entities and 32 components limit. But there is still hash collision with
> 
> ```cs
>   var entity = World.Create(new Name { Value = "SkySystemData" });
>         entity.Add(skyData);
>         entity.Add(sun);
> ```
> 
> it asserts on
> 
> ```
>     [MethodImpl(MethodImplOptions.AggressiveInlining)]
>     internal void Move(Entity entity, Archetype source, Archetype destination, out Slot destinationSlot)
>     {
>         // A common mistake, happening in many cases.
>         Debug.Assert(source != destination, "From-Archetype is the same as the To-Archetype. Entities cannot move within the same archetype using this function. Probably an attempt was made to attach already existing components to the entity or to remove non-existing ones.");
> 
> 
> ---- DEBUG ASSERTION FAILED ----
> ---- Assert Short Message ----
> From-Archetype is the same as the To-Archetype. Entities cannot move within the same archetype using this function. Probably an attempt was made to attach already existing components to the entity or to remove non-existing ones.
> ---- Assert Long Message ----
> ```
> 
> But doing
> 
> ```cs
>   var entity = World.Create(skyData);
>         entity.Add(sun);
>         entity.Add(new Name { Value = "SkySystemData" });
> ```
> 
> Works... Or if using another hash function.

Sooo i did a thing and implemented MurMurHash3 :) 
The tests do run fine, the sample also runs. Looks like it works.

Could you try it out to see if the issue with the SkyData e.g. persists? ^^

**Comment by clibequilibrium** [comment]
> > > 
> > 
> > 
> > Sadly it does. So your PR fixes the deletion of entities and 32 components limit. But there is still hash collision with
> > ```cs
> >   var entity = World.Create(new Name { Value = "SkySystemData" });
> >         entity.Add(skyData);
> >         entity.Add(sun);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it asserts on
> > ```
> >     [MethodImpl(MethodImplOptions.AggressiveInlining)]
> >     internal void Move(Entity entity, Archetype source, Archetype destination, out Slot destinationSlot)
> >     {
> >         // A common mistake, happening in many cases.
> >         Debug.Assert(source != destination, "From-Archetype is the same as the To-Archetype. Entities cannot move within the same archetype using this function. Probably an attempt was made to attach already existing components to the entity or to remove non-existing ones.");
> > 
> > 
> > ---- DEBUG ASSERTION FAILED ----
> > ---- Assert Short Message ----
> > From-Archetype is the same as the To-Archetype. Entities cannot move within the same archetype using this function. Probably an attempt was made to attach already existing components to the entity or to remove non-existing ones.
> > ---- Assert Long Message ----
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But doing
> > ```cs
> >   var entity = World.Create(skyData);
> >         entity.Add(sun);
> >         entity.Add(new Name { Value = "SkySystemData" });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Works... Or if using another hash function.
> 
> Sooo i did a thing and implemented MurMurHash3 :) The tests do run fine, the sample also runs. Looks like it works.
> 
> Could you try it out to see if the issue with the SkyData e.g. persists? ^^

Sadly it's still happening , I will create a new ticket with a repro if I can trace why it occurs. 

Thanks !

**Comment by genaray** [comment]
Thanks for checking! 
Damn... I thought its finally solved. Why the heck does it return zero? Probably the combination of the bits 4,31,32 could reproduce this bug.

Gonna check this locally ^^

**Comment by genaray** [comment]
Sooo there was another issue, some method calculated the amount of required uints to store a certain bitflag the wrong way. Lets see if this could finally fix it ^^ 

Please test it and let me know if its gone now... otherwise I'll jump from the next bridge xD

**Comment by clibequilibrium** [comment]
You got it  ! 🔥  works like a charm

Thank you so so much for your example over the last few days. I am so happy to see Arch getting battle tested and getting stronger !

**Comment by genaray** [comment]
Thanks, damn that just saved me from jumping of the bridge ;)

**Comment by clibequilibrium** [comment]
> Thanks, damn that just saved me from jumping of the bridge ;)

Well I will keep you posted XD
